const CREATE_ACTIVITY = 'CREATE-ACTIVITY';
const UPDATE_ACTIVITY = 'UPDATE-ACTIVITY';
const DELETE_ACTIVITY = 'DELETE-ACTIVITY';
const GET_ALL_ACTIVITIES = 'GET-ALL-ACTIVITIES';
const SET_FILTER_BY_ACTIVITY = 'SET-FILTER-BY-ACTIVITY';
const SET_NEW_ACTIVITY = 'SET-NEW-ACTIVITY';

export { 
  CREATE_ACTIVITY, 
  UPDATE_ACTIVITY,
  DELETE_ACTIVITY,
  GET_ALL_ACTIVITIES,
  SET_FILTER_BY_ACTIVITY,
  SET_NEW_ACTIVITY
};
