const SET_CURRENT_PAGE = 'SET-CURRENT-PAGE';
const SET_ORDER = 'SET-ORDER';
const SET_FILTER_BY_CONTINENTS = 'SET-FILTER-BY-CONTINENTS';
const SET_ERROR = 'SET-ERROR';

export {
    SET_CURRENT_PAGE,
    SET_ORDER,
    SET_FILTER_BY_CONTINENTS,
    SET_ERROR
};