const GET_ALL_COUNTRIES = 'GET-ALL-COUNTRIES';
const GET_COUNTRIES_BY_NAME = 'GET-COUNTRIES-BY-NAME';
const SET_CURRENT_COUNTRIES = 'SET-CURRENT-COUNTRIES';

export {
    GET_ALL_COUNTRIES,
    GET_COUNTRIES_BY_NAME,
    SET_CURRENT_COUNTRIES
};